# Generated by Django 5.2.14 on 2026-05-29 09:17

import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual_pop', 'Manual / Bank Transfer (Proof of Payment)'), ('paynow', 'Paynow'), ('ecocash', 'EcoCash'), ('stripe', 'Stripe')], default='manual_pop', max_length=32)),
                ('purpose', models.CharField(choices=[('trust_deposit', 'Trust / Escrow Deposit'), ('consultation', 'Consultation Fee'), ('invoice', 'Invoice Settlement'), ('retainer', 'Retainer')], default='trust_deposit', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reference', models.CharField(blank=True, help_text='Bank / provider transaction reference.', max_length=256)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Uploaded proof of payment (PDF or image).', null=True, upload_to=payments.models.proof_of_payment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_review', max_length=32)),
                ('note', models.TextField(blank=True, help_text='Payer-supplied note about the payment.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Reviewer decision note.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.matter')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('trust_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='core.trusttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['matter', 'status'], name='payments_pa_matter__23ddcd_idx')],
            },
        ),
    ]
