# Generated by Django 5.2.14 on 2026-06-13 08:24

import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


def backfill_receipts(apps, schema_editor):
    """Convert each existing Payment with a proof file into one
    PaymentReceipt for the payment's full amount, mirroring its review
    state. Payments without a proof are left as-is (no receipts)."""
    Payment = apps.get_model('payments', 'Payment')
    PaymentReceipt = apps.get_model('payments', 'PaymentReceipt')
    for p in Payment.objects.exclude(proof_of_payment='').exclude(proof_of_payment=None):
        if p.receipts.exists():
            continue
        PaymentReceipt.objects.create(
            payment=p,
            amount=p.amount,
            proof_of_payment=p.proof_of_payment,
            reference=p.reference or '',
            note=p.note or '',
            status=p.status if p.status in {'verified', 'rejected', 'pending_review'} else 'pending_review',
            review_note=p.review_note or '',
            reviewed_by=p.reviewed_by,
            reviewed_at=p.reviewed_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('partial', 'Partial'), ('verified', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_review', max_length=32),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proof_of_payment', models.FileField(upload_to=payments.models.receipt_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('reference', models.CharField(blank=True, max_length=256)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('partial', 'Partial'), ('verified', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_review', max_length=32)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', 'status'], name='payments_pa_payment_fd5408_idx')],
            },
        ),
        migrations.RunPython(backfill_receipts, migrations.RunPython.noop),
    ]
