# Generated by Django 5.2.14 on 2026-06-09 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('case', 'Case'), ('judgement', 'Judgement'), ('rules', 'High Court Rules'), ('constitution', 'Constitution'), ('statute', 'Statute')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorpusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('citation', models.CharField(blank=True, max_length=240)),
                ('jurisdiction', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corpus.corpuscollection')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CorpusChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='corpus.corpusdocument')),
            ],
            options={
                'ordering': ['document_id', 'ordinal'],
                'unique_together': {('document', 'ordinal')},
            },
        ),
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('scope', models.JSONField(default=list)),
                ('answer_text', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.corpuschunk')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='corpus.researchquery')),
            ],
            options={
                'ordering': ['query_id', 'rank'],
            },
        ),
    ]
