# Generated by Django 5.2.14 on 2026-06-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcitation',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researchcitation',
            name='source_kind',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='researchcitation',
            name='source_title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='researchcitation',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='corpus.corpuschunk'),
        ),
    ]
