# Generated by Django 5.2.14 on 2026-05-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_firm_admin_firm_default_consultation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='practising_certificate_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='practising_certificate_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
