# Generated by Django 5.2.14 on 2026-05-31 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lawyerprofile_practising_certificate_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='id_document_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_licence', "Driver's licence")], max_length=24),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Inline signature payload (base64 PNG or text).'),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='practising_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certs/'),
        ),
        migrations.CreateModel(
            name='MatterInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254)),
                ('sent_to_phone', models.CharField(blank=True, max_length=32)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.matter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matter_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invite', 'Invite'), ('booking', 'Booking'), ('payment', 'Payment'), ('document', 'Document'), ('generic', 'Generic')], default='generic', max_length=16)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=240)),
                ('sent_email', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
