# Generated by Django 5.2.14 on 2026-06-08 18:47

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_parent_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='id_document_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc/', validators=[core.validators.validate_doc]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.matter_document_path, validators=[core.validators.validate_doc]),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='practising_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certs/', validators=[core.validators.validate_doc]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[core.validators.validate_avatar]),
        ),
    ]
