# Generated by Django 5.2.14 on 2026-06-08 20:55

from collections import Counter

from django.db import migrations, models


# Conservative name → ISO 3166-1 alpha-2 map. Only includes countries we're
# likely to see in jurisdiction strings; unknowns leave the field blank.
NAME_TO_ISO = {
    'zimbabwe': 'ZW',
    'south africa': 'ZA',
    'sa': 'ZA',
    'rsa': 'ZA',
    'botswana': 'BW',
    'namibia': 'NA',
    'zambia': 'ZM',
    'malawi': 'MW',
    'mozambique': 'MZ',
    'kenya': 'KE',
    'tanzania': 'TZ',
    'uganda': 'UG',
    'rwanda': 'RW',
    'nigeria': 'NG',
    'ghana': 'GH',
    'ethiopia': 'ET',
    'egypt': 'EG',
    'morocco': 'MA',
    'united states': 'US',
    'usa': 'US',
    'united kingdom': 'GB',
    'uk': 'GB',
    'england': 'GB',
    'scotland': 'GB',
    'ireland': 'IE',
    'australia': 'AU',
    'canada': 'CA',
    'india': 'IN',
    'china': 'CN',
    'france': 'FR',
    'germany': 'DE',
    'spain': 'ES',
    'italy': 'IT',
    'netherlands': 'NL',
    'portugal': 'PT',
    'brazil': 'BR',
    'mexico': 'MX',
    'uae': 'AE',
    'united arab emirates': 'AE',
}


def _to_iso(jurisdiction):
    if not jurisdiction:
        return ''
    key = jurisdiction.strip().lower()
    return NAME_TO_ISO.get(key, '')


def backfill(apps, schema_editor):
    LawyerProfile = apps.get_model('core', 'LawyerProfile')
    Firm = apps.get_model('core', 'Firm')

    # Lawyers: take the first matchable jurisdiction.
    for profile in LawyerProfile.objects.all():
        if profile.country:
            continue
        for j in (profile.jurisdictions or []):
            iso = _to_iso(j)
            if iso:
                profile.country = iso
                profile.save(update_fields=['country'])
                break

    # Firms: majority vote over their lawyers' countries.
    for firm in Firm.objects.all():
        if firm.country:
            continue
        codes = [p.country for p in firm.lawyers.all() if p.country]
        if codes:
            firm.country = Counter(codes).most_common(1)[0][0]
            firm.save(update_fields=['country'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_two_factor_method_user_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
