# Generated by Django 5.2.14 on 2026-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_firm_country_lawyerprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular message'), ('milestone', 'Matter milestone')], default='regular', max_length=16),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
