# Generated by Django 5.2.14 on 2026-06-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message_kind_alter_consultation_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='payments.payment'),
        ),
    ]
