# Generated by Django 5.2.14 on 2026-06-13 08:51

from decimal import Decimal

from django.db import migrations, models


# Bar-association brackets from the Law Society of Zimbabwe — used as the
# platform-wide default (country='') because every region typically has a
# similar tier shape. Each row is (min_years, max_years, hourly_min, hourly_max).
DEFAULT_TIERS = [
    (30, None, '310.00', '350.00'),
    (20, 29, '270.00', '310.00'),
    (15, 19, '210.00', '270.00'),
    (10, 14, '150.00', '210.00'),
    (5, 9, '120.00', '150.00'),
    (2, 4, '90.00', '120.00'),
    (0, 1, '60.00', '90.00'),
]


def seed_default_tiers(apps, schema_editor):
    LawyerRateTier = apps.get_model('core', 'LawyerRateTier')
    LawyerProfile = apps.get_model('core', 'LawyerProfile')
    for min_y, max_y, hmin, hmax in DEFAULT_TIERS:
        LawyerRateTier.objects.update_or_create(
            country='', min_years=min_y,
            defaults={
                'max_years': max_y,
                'hourly_min': Decimal(hmin),
                'hourly_max': Decimal(hmax),
                'currency': 'USD',
                'note': 'Law Society of Zimbabwe basic hourly ranges (platform default).',
            },
        )

    # Backfill existing lawyer profiles so their hourly_rate matches the
    # new tiers — useful for the demo dataset and any prior real data.
    for profile in LawyerProfile.objects.all():
        years = profile.years_experience or 0
        country = profile.country or ''
        tier = (
            LawyerRateTier.objects.filter(country=country, min_years__lte=years).order_by('-min_years').first()
            or LawyerRateTier.objects.filter(country='', min_years__lte=years).order_by('-min_years').first()
        )
        if tier is None:
            continue
        if tier.max_years is not None and years > tier.max_years:
            continue
        midpoint = (tier.hourly_min + tier.hourly_max) / Decimal('2')
        profile.hourly_rate = midpoint.quantize(Decimal('0.01'))
        profile.save(update_fields=['hourly_rate'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_timeentry_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerRateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('min_years', models.PositiveSmallIntegerField()),
                ('max_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hourly_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', '-min_years'],
                'constraints': [models.UniqueConstraint(fields=('country', 'min_years'), name='unique_country_min_years')],
            },
        ),
        migrations.RunPython(seed_default_tiers, migrations.RunPython.noop),
    ]
