# Generated by Django 5.2.14 on 2026-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lawyerratetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='practising_certificate_issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
