# Generated by Django 5.2.14 on 2026-08-21 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lawyerprofile_practising_certificate_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='monthly_retainer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='retainer',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainers', to='core.matter'),
        ),
        migrations.AddField(
            model_name='retainer',
            name='next_invoice_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
