# Generated by Django 5.2.14 on 2026-08-30 14:17

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_version', models.PositiveIntegerField(default=1)),
                ('mobile_latest_build', models.PositiveIntegerField(default=1)),
                ('mobile_min_build', models.PositiveIntegerField(default=1)),
                ('ios_store_url', models.URLField(blank=True)),
                ('android_store_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App config',
                'verbose_name_plural': 'App config',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_check', models.BooleanField(default=False)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription settings',
                'verbose_name_plural': 'Subscription settings',
            },
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='subscription_override',
            field=models.CharField(choices=[('inherit', 'Inherit global'), ('on', 'Always enforce'), ('off', 'Exempt')], default='inherit', max_length=8),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_review', max_length=16)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='subscriptions/', validators=[core.validators.validate_doc])),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'unique_together': {('user', 'period_start')},
            },
        ),
    ]
