# Generated by Django 5.2.14 on 2026-06-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_token_quota', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pool_disabled', models.BooleanField(default=False, help_text='When True the user must BYOK; pool-key fallback is denied.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (ChatGPT)'), ('local', 'Local / self-hosted (Ollama-compatible)')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('pool', models.BooleanField(default=False, help_text='True when served by the platform pool key.')),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='workflows_l_owner_i_1b7c2c_idx'), models.Index(fields=['pool', '-created_at'], name='workflows_l_pool_f0a17a_idx')],
            },
        ),
    ]
