# Generated by Django 5.2.14 on 2026-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_llmuserquota_llmusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmuserquota',
            name='daily_token_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Max tokens this user may spend per calendar day. Blank = platform default.', null=True),
        ),
        migrations.AddField(
            model_name='llmuserquota',
            name='weekly_token_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Max tokens this user may spend per ISO week (Mon–Sun). Blank = platform default.', null=True),
        ),
        migrations.AlterField(
            model_name='llmuserquota',
            name='is_pool_disabled',
            field=models.BooleanField(default=False, help_text='When True the user is blocked from the shared AI provider entirely.'),
        ),
        migrations.AlterField(
            model_name='llmuserquota',
            name='monthly_token_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Max tokens this user may spend per calendar month. Blank = platform default.', null=True),
        ),
    ]
