# Generated by Django 5.2.14 on 2026-06-20 15:14

import django.core.validators
import django.db.models.deletion
import workflows.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lawyerratetier'),
        ('workflows', '0003_llmuserquota_daily_token_quota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('token_credits', models.PositiveBigIntegerField(help_text='AI tokens granted to the account when an order for this plan is verified.')),
                ('period', models.CharField(choices=[('one_time', 'One-time top-up'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='one_time', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='AIPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_token_quota', models.PositiveIntegerField(default=20000)),
                ('weekly_token_quota', models.PositiveIntegerField(default=60000)),
                ('monthly_token_quota', models.PositiveIntegerField(default=200000)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI platform settings',
                'verbose_name_plural': 'AI platform settings',
            },
        ),
        migrations.CreateModel(
            name='AICreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, help_text='Current AI token balance. May dip slightly negative if a call overshoots.')),
                ('lifetime_granted', models.PositiveBigIntegerField(default=0)),
                ('lifetime_spent', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_firm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_account', to='core.firm')),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AICreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_credits', models.PositiveBigIntegerField(help_text='Credits granted on verification. Defaults from the plan; override for ad-hoc grants.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reference', models.CharField(blank=True, help_text='Bank / mobile-money reference.', max_length=256)),
                ('method', models.CharField(blank=True, help_text='ecocash / innbucks / bank / cash / other.', max_length=32)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Uploaded proof of payment (PDF or image).', null=True, upload_to=workflows.models.ai_credit_pop_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('note', models.TextField(blank=True, help_text='Payer-supplied note.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_orders', to='core.firm')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_orders', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_credit_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='workflows.aicreditplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grant', 'Grant (purchase verified)'), ('debit', 'Debit (AI usage)'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment'), ('expiry', 'Expiry')], max_length=16)),
                ('amount', models.BigIntegerField(help_text='Signed token delta: +grant, -debit.')),
                ('balance_after', models.BigIntegerField()),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workflows.aicreditaccount')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_credit_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='workflows.aicreditorder')),
                ('usage_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='workflows.llmusagelog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aicreditaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_firm__isnull', True), ('owner_user__isnull', False)), models.Q(('owner_firm__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='ai_credit_account_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='aicreditorder',
            index=models.Index(fields=['status', '-created_at'], name='workflows_a_status_4c9121_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicreditorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_firm__isnull', True), ('owner_user__isnull', False)), models.Q(('owner_firm__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='ai_credit_order_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='aicredittransaction',
            index=models.Index(fields=['account', '-created_at'], name='workflows_a_account_263765_idx'),
        ),
    ]
