# Generated by Django 5.2.14 on 2026-06-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_aicreditplan_aiplatformsettings_aicreditaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicreditorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The lawyer who submitted this order (notified on verify/reject).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ai_credit_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
