# Generated by Django 5.2.14 on 2026-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_aicreditorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicreditaccount',
            name='free_tier_granted',
            field=models.BooleanField(default=False, help_text='Whether the one-time free-tier credits have been granted to this account.'),
        ),
        migrations.AddField(
            model_name='aiplatformsettings',
            name='free_tier_credits',
            field=models.PositiveIntegerField(default=10000, help_text='AI credits granted once, for free, to every new lawyer/firm account before they buy a plan. Set to 0 to disable the free tier.'),
        ),
    ]
