# Generated by Django 5.2.14 on 2026-06-20 19:10

import workflows.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_precedenttemplate_workflowdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicredittransaction',
            name='kind',
            field=models.CharField(choices=[('grant', 'Grant (purchase verified)'), ('hold', 'Hold (reservation for an AI run)'), ('debit', 'Debit (AI usage)'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment'), ('expiry', 'Expiry')], max_length=16),
        ),
        migrations.AlterField(
            model_name='llmproviderconfig',
            name='api_key',
            field=workflows.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
