# Generated by Django 5.2.14 on 2026-06-20 19:11

from django.db import migrations

from workflows.fields import _PREFIX, encrypt


def encrypt_existing(apps, schema_editor):
    """Encrypt any legacy plaintext API keys in place. Uses raw SQL so we read
    and write the actual column bytes without the field's encrypt/decrypt layer."""
    table = apps.get_model('workflows', 'LLMProviderConfig')._meta.db_table
    conn = schema_editor.connection
    with conn.cursor() as cur:
        cur.execute(f'SELECT id, api_key FROM {table}')  # noqa: S608 — table from meta
        rows = cur.fetchall()
        for pk, val in rows:
            if not val or str(val).startswith(_PREFIX):
                continue
            cur.execute(
                f'UPDATE {table} SET api_key = %s WHERE id = %s',  # noqa: S608
                [encrypt(val), pk],
            )


def noop_reverse(apps, schema_editor):
    # Decryption-on-read keeps things working; nothing to undo destructively.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_alter_aicredittransaction_kind_and_more'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing, noop_reverse),
    ]
