# Generated by Django 5.2.14 on 2026-06-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lawyerratetier'),
        ('workflows', '0010_contractreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractreview',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='sent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.document'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='sent_matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.matter'),
        ),
    ]
