# Generated by Django 5.2.14 on 2026-07-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_contractreview_sent_at_contractreview_sent_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmproviderconfig',
            options={'ordering': ['provider', 'label'], 'verbose_name': 'AI Provider', 'verbose_name_plural': 'AI Providers'},
        ),
    ]
